services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jurparkdb
      MYSQL_USER: nedry
      MYSQL_PASSWORD: ahahah
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Initial SQL script to set up the database

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver-container
    restart: always
    environment:
      CB_SERVER_NAME: "jurparkdbserver"
    ports:
      - "8080:8978"
    depends_on:
      - mariadb
    volumes:
      - ./initial-data-sources.conf:/opt/cloudbeaver/workspace/initial-data-sources.conf:ro

volumes:
  mariadb_data: